More build warnings.
cardano-scaling/alba pull request #47
Opened 2024-10-30 14:53 UTC by tolikzinovyev

This enables additional rustc lints. Their description can be found here: https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html.

2024-10-31 09:31 UTC, rrtoledo submitted a review, later dismissed

2024-10-31 10:56 UTC, djetchev submitted a review, later dismissed
lgtm

2024-10-31 14:10 UTC, curiecrypt requested changes
We should also add warnings for the `dead_code` and `unused_variables`

2024-10-31 23:49 UTC, tolikzinovyev commented
> We should also add warnings for the `dead_code` and `unused_variables`

Those are enabled by default. https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html

2024-11-01 00:30 UTC, tolikzinovyev commented
@curiecrypt feel free to merge this if there are no more objections.

2024-11-04 14:57 UTC, curiecrypt approved these changes
LGTM

2024-11-04 16:10 UTC, djetchev approved these changes
lgtm

2024-11-05 15:18 UTC, merged