Setup structure for lottery scheme
cardano-scaling/alba pull request #58
Opened 2024-11-06 16:04 UTC by curiecrypt

## Content

This PR includes the setup structure for the simple lottery construction. 

## Pre-submit checklist

- Branch
    - [X] Commit sequence broadly makes sense
    - [X] Key commits have useful messages
- PR
    - [X] No clippy warnings in the CI
    - [X] Self-reviewed the diff
    - [X] Useful pull request description
    - [X] Reviewer requested
## Comments

## Issue(s)

Relates to #37

2024-11-06 19:47 UTC, tolikzinovyev requested changes
Could you make a pull request with the main branch as the target? Right now it targets your `curiecrypt/simplelottery` branch.

2024-11-07 14:30 UTC, tolikzinovyev reviewed
Can you please rebase the branch also?

2024-11-07 14:30 UTC, tolikzinovyev commented on src/simple_lottery/mod.rs
> +//! Simple lottery construction for the Telescope ALBA  scheme.
nit
```suggestion
//! Simple lottery construction for the Telescope ALBA scheme.
```

2024-11-07 14:30 UTC, tolikzinovyev commented on src/simple_lottery/setup.rs
> +pub struct LotterySetup {
Could we name it `Setup` to be consistent with centralized telescope?

2024-11-07 15:30 UTC, tolikzinovyev approved these changes
LGTM

2024-11-07 16:26 UTC, rrtoledo approved these changes

2024-11-07 16:27 UTC, merged